hlxsites/sgws-creative

- fstab.yaml
- package-lock.json
- styles/styles.css
Fix #2
- After: https://fstab--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
- use Adobe sharepoint as placeholder
> Update fstab to correct content location #2

- blocks/fragment/fragment.css
- blocks/fragment/fragment.js
Fix https://github.com/hlxsites/sgws-creative/issues/13
- Before: https://main--sgws-creative--hlxsites.hlx.page/drafts/mathern/fragment
- After: https://issue-13-fragment--sgws-creative--hlxsites.hlx.page/drafts/mathern/fragment
- Adds a fragment block
Authoring experience:
> Issue 13: Fragment block

- blocks/video/video.css
- blocks/video/video.js
Fix https://github.com/hlxsites/sgws-creative/issues/36
- Before: https://main--sgws-creative--hlxsites.hlx.page/drafts/mathern/video
- After: https://issue-3-hero--sgws-creative--hlxsites.hlx.page/drafts/mathern/video
- Adds a video block with an authorable poster image.
Authoring experience:
> Issue 36: Video with poster block

- scripts/scripts.js
- styles/styles.css
Fix #6
- After: https://video-section--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
- extend `buildHeroSection` to apply to any section
> Video section #6

- README.md
- blocks/columns/columns.css
- blocks/footer/footer.css
- blocks/fragment/fragment.js
- blocks/tabview/tabview.css
- blocks/video/video.css
- scripts/lib-franklin.js
- scripts/scripts.js
- styles/lazy-styles.css
- styles/styles.css
Fix #45
- After: https://theming--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
- After: https://theming--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6
- add theming to product templates
- CSS cleanup
- allow fragments to have multiple sections
> fix: Theming Support #45

- scripts/scripts.js
- Before: https://main--sgws-creative--hlxsites.hlx.page/drafts/top/showcase-5
- After: https://empty-theme--sgws-creative--hlxsites.hlx.page/drafts/top/showcase-5
> chore: fix font loading when there is no theme

- scripts/scripts.js
- styles/styles.css
Fix #58 
- After: https://bordergap--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
removed the border gap
> border shows a gap when browser window is scaled down

- README.md
- blocks/columns/columns.css
- blocks/columns/columns.js
- blocks/footer/footer.css
- blocks/footer/footer.js
- blocks/tabview/tabview.css
- scripts/scripts.js
- styles/lazy-styles.css
- styles/styles.css
Fix #57
- After: https://block-theme--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
- remove stats vars from theme
- allow stats background image to come from content
- introduce new styles to control stats layout
> fix: Remove block specific vars from theme #57

- blocks/columns/columns.css
Fix #81 
- After: https://statswidth--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
fixed the width issue
> stats width misalignment

- blocks/columns/columns.css
- blocks/columns/columns.js
- blocks/portfolio/portfolio.css
- blocks/portfolio/portfolio.js
- blocks/slides/slides.css
- blocks/slides/slides.js
- blocks/tabview/tabview.css
- scripts/scripts.js
- styles/styles.css
Fix #60
- After: https://animations--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
- added default animation processing for pages
> feat: Add animations to presentation pages #60

- blocks/portfolio/portfolio.css
Fix #62
- Before: https://main--sgws-creative--hlxsites.hlx.page/drafts/arumsey/portfolio
- After: https://portfolio-images--sgws-creative--hlxsites.hlx.page/drafts/arumsey/portfolio
- fix aspect ratio
- fix sizing
> fix: Portfolio block: Fix image sizing for all screen widths #62

- blocks/slides/slides.css
- blocks/tabview/tabview.js
- blocks/video/video.css
- blocks/video/video.js
- scripts/scripts.js
Fix N/A
- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/3-tmn-draft
- After: https://issue-95--sgws-creative--hlxsites.hlx.page/bloominbrands/p/3-tmn-draft
- Fix badge overlapping with "pairs with" content
> Badge bugfix

- blocks/slides/slides.css
- blocks/slides/slides.js
- blocks/tabview/tabview.css
- blocks/tabview/tabview.js
Fix #71 
- After: https://issue-71--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
> Issue 71: Stats block as slide fragment

- blocks/tabview/tabview.css
- blocks/tabview/tabview.js
Fix #103 
- After: https://issue-103--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
> Issue 103: product border

- blocks/video/video.css
- blocks/video/video.js
- scripts/scripts.js
- styles/styles.css
Fix #110 
- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6
- After: https://issue-110--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6
> Issue 110: Stats on product pages is invisible

- blocks/footer/footer.css
- blocks/footer/footer.js
- styles/styles.css
Fix #111
- Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6
- After: https://broken_foot111--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6
Original:  https://sgcreative.southernglazers.com/bloominbrands/p/6
Make a product's footer appear as the original product page.
I tried to isolate it to the product's footer specifically, to not interfere with other footers.
Made some judgement calls - It is very close.
> Broken foot #111

- blocks/tabview/tabview.js
- styles/styles.css
Fix #116 
- After: https://issue-116--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
remove theme specific value from css
> Remove theme specific value from css

- blocks/billboard/billboard.css
- blocks/slides/slides.css
- blocks/tabview/tabview.css
Fix #112
- After: https://slide-height--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
Tweaked div and image sizes to make everything (hopefully) consistently the same height
> Slide height

- blocks/chart-map/chart-map.js
- blocks/video/video.js
- scripts/scripts.js
Fix N/A
- Before: https://main--sgws-creative--hlxsites.hlx.page/drafts/mathern/2
- After: https://review-comments-1--sgws-creative--hlxsites.hlx.page/drafts/mathern/2
Remove magic numbers
> Use constants for default video image placeholder size

- blocks/billboard/billboard.js
- blocks/poster/poster.js
- blocks/tabview/tabview.js
- scripts/scripts.js
Fix Improve perf.
- Before: https://main--sgws-creative--hlxsites.hlx.page/drafts/mathern/2
- After: https://perfs--sgws-creative--hlxsites.hlx.page/drafts/mathern/2
- After: https://perfs--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
> Set theme styles only once (all at once)

- blocks/columns/columns.css
- styles/styles.css
Fixes:
- #128 
- #129 
- After: https://wwa-layout--sgws-creative--hlxsites.hlx.page/bloominbrands/p/1
Adjusted columns styling and added a new animation variant to clip the bottom edge of the content while it moves up
> Wwa layout

- blocks/columns/columns.css
- blocks/columns/columns.js
- blocks/footer/footer.css
- blocks/footer/footer.js
Issue
Fix https://github.com/hlxsites/sgws-creative/issues/17
🔗 Test URLs:
Before: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/5
After: https://blindfold17--sgws-creative--hlxsites.hlx.page/bloominbrands/p/5
📝 Description:
Tweaks to make the Blindfold product page work, especially allow the video to not animate. I tried to isolate it as much as possible.
Check lower video components in here as well (left & right of the screen, lower):
https://blindfold17--sgws-creative--hlxsites.hlx.page/bloominbrands/p/5
> Author: Blindfold product page #17
